### ISSUE TITLE
Vitest: Error: Missing "./messages" export in "@intlify/vite-plugin-vue-i18n" package

### ISSUE THREAD

**Issue by yooouuri** [intlify/bundle-tools#145] opened 2022-07-15 07:38 UTC
### Reporting a bug?

I use `@intlify/vite-plugin-vue-i18n` to load my translation files.

When I run Vitest, im getting the following error:

> Error: Missing "./messages" export in "@intlify/vite-plugin-vue-i18n" package

When I run `vite` or `vite build`, everything works as expected.

### Expected behavior

The tests are using my translations.

### Reproduction

vite.config.ts
```typescript
import vueI18n from '@intlify/vite-plugin-vue-i18n'
import vue from '@vitejs/plugin-vue'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'url'
import { defineConfig } from 'vitest/config'
import GithubActionsReporter from 'vitest-github-actions-reporter'

export default defineConfig({
  plugins: [
    vue(),
    vueI18n({
      include: resolve(dirname(fileURLToPath(import.meta.url)), './src/locales/**'),
    }),
  ],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url)),
    },
  },
  test: {
    globals: true,
    environment: 'jsdom',
    include: ['**/*.unit.ts'],
    setupFiles: ['./tests/unit/setup.ts'],
    reporters: process.env.GITHUB_ACTIONS !== undefined ? new GithubActionsReporter() : 'default',
    coverage: {
      reporter: 'lcov',
    },
  },
})
```

tests/unit/setup.ts
```typescript
import '@testing-library/jest-dom'

import { config } from '@vue/test-utils'

import { i18n } from '@/i18n'

beforeAll(() => {
  // some mocks
  vi.mock('chart.js', () => ({
    registerables: [],
    Chart: {
      register: () => null,
    },
  }))

  config.global.plugins = [ i18n ]
})
```

@/i18n.ts
```typescript
import messages from '@intlify/vite-plugin-vue-i18n/messages'
import { createI18n } from 'vue-i18n'

export const i18n = createI18n({
  locale: 'nl',
  fallbackLocale: 'en',
  legacy: false,
  messages,
})
```

### Issue Package

vite-plugin-vue-i18n

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1 Pro
    Memory: 82.83 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.1 - /opt/homebrew/opt/node@16/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.11.0 - /opt/homebrew/opt/node@16/bin/npm
  Browsers:
    Firefox: 102.0.1
    Safari: 15.5
  npmPackages:
    @intlify/vite-plugin-vue-i18n: ^5.0.0 => 5.0.0
    vite: ^3.0.0 => 3.0.0
    vue: ^3.2.0 => 3.2.37
    vue-i18n: 9 => 9.1.10
```

### Screenshot

![image](https://user-images.githubusercontent.com/12934957/179175746-77449962-f7dc-44eb-a293-fb6bf156d751.png)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/bundle-tools/blob/main/.github/contributing.md).
- [X] Read the README
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/bundle-tools/discussions).

**Comment by kazupon** [comment] 2022-07-16 04:50
Thank you for your reporting!

Unfortunately, I could not reproduce this issue 😞 
so, I seem that your reproduction codes include the domain-specific codes (e.g. GithubActionsReporter).
Could you give us minimum reproduction codes, please? 🙏

**Comment by marekvospel** [comment] 2022-07-20 22:07
Got the same issue with the following dependencies
![image](https://user-images.githubusercontent.com/73162071/180090591-748dd720-967c-4a36-98db-222fafd2f515.png)

I've created a minimum reproduction repository @kazupon 
https://github.com/marekvospel/vitest-vite-plugin-vue-i18n

I used pnpm, but the issue also happens with npm & yarn

**Comment by kazupon** [comment] 2022-07-20 23:01
Thanks!
I could see this issue

**Comment by mHooshdar** [comment] 2022-07-24 20:13
These changes and the latest release do not fix the problem

I have a problem with building the project too. it said:

```
import { createI18n, useI18n } from "vue-i18n/dist/vue-i18n.runtime.esm-bundler.js";
         ^^^^^^^^^^
SyntaxError: Named export 'createI18n' not found. The requested module 'vue-i18n/dist/vue-i18n.runtime.esm-bundler.js' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'vue-i18n/dist/vue-i18n.runtime.esm-bundler.js';
const { createI18n, useI18n } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:194:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:409:24)
    at async build (file:///Users/mhooshdar/Desktop/Projects/vuilerplate/node_modules/.pnpm/vite-ssg@0.20.2_bc535nzjtcqlryzrekyvursaoq/node_modules/vite-ssg/dist/chunks/build.mjs:171:87)
    at async Object.handler (file:///Users/mhooshdar/Desktop/Projects/vuilerplate/node_modules/.pnpm/vite-ssg@0.20.2_bc535nzjtcqlryzrekyvursaoq/node_modules/vite-ssg/dist/node/cli.mjs:20:3)
```

**Comment by alfeg** [comment] 2022-07-25 06:32
Not sure what I'm doing wrong
But the fix don't help
```
FATAL ERROR: v8::ToLocalChecked Empty MaybeLocal.
 1: 00007FF7479F7C4F v8::internal::CodeObjectRegistry::~CodeObjectRegistry+114207
 2: 00007FF747985EC6 DSA_meth_get_flags+65542
 3: 00007FF747986D7D node::OnFatalError+301
 4: 00007FF7482C41E5 v8::V8::ToLocalEmpty+53
 5: 00007FF74797DF66 DSA_meth_get_flags+32934
 6: 00007FF7479718CB v8::base::CPU::has_sse+42283
 7: 00007FF747A5ABC7 uv_timer_stop+1207
 8: 00007FF747A5715B uv_async_send+331
 9: 00007FF747A568EC uv_loop_init+1292
10: 00007FF747A56A8A uv_run+202
11: 00007FF747A258F5 node::SpinEventLoop+309
12: 00007FF7478BE520 v8::internal::interpreter::BytecodeLabel::bind+35712
13: 00007FF7478B9B78 v8::internal::interpreter::BytecodeLabel::bind+16856
14: 00007FF747A4715D uv_poll_stop+557
15: 00007FF748860740 v8::internal::compiler::RepresentationChanger::Uint32OverflowOperatorFor+146416
16: 00007FF87F3F54E0 BaseThreadInitThunk+16
17: 00007FF880CC485B RtlUserThreadStart+43
```
Provided repro from @marekvospel is failing too after packages update to the latest: https://github.com/marekvospel/vitest-vite-plugin-vue-i18n

**Comment by yooouuri** [comment] 2022-07-25 07:00
Sadly the fix also didn't work for me

**Comment by kazupon** [comment] 2022-07-25 07:29
Yeah, Unfortunately, I could not still resolve this issue 😞 
`@intlify/vite-plugin-vue-i18n/messages` is virtual module of `@intlify/vite-plugin-vue-i18` plugin

I recognize that the virtual module is automatically externalized in SSR.
However, it seems that vite is not done.

**Comment by kazupon** [comment] 2022-07-25 15:08
That seems to be a bug of Vite SSR
ref: github discussions on
https://github.com/vitejs/vite/discussions/9356

ref: github issues on vite
https://github.com/vitejs/vite/issues/9364

**Comment by kazupon** [comment] 2022-07-29 14:09
Thank you for your taking the time to let us know!
Okay, I'll close this issue.

**Closed by kazupon** 2022-07-29 14:09 UTC
Labels: Status: Need More Info, Package: vite-plugin-vue-i18n

**Comment by chemeng** [comment] 2022-08-03 09:49
> These changes and the latest release do not fix the problem
> 
> I have a problem with building the project too. it said:
> 
> ```
> import { createI18n, useI18n } from "vue-i18n/dist/vue-i18n.runtime.esm-bundler.js";
>          ^^^^^^^^^^
> SyntaxError: Named export 'createI18n' not found. The requested module 'vue-i18n/dist/vue-i18n.runtime.esm-bundler.js' is a CommonJS module, which may not support all module.exports as named exports.
> CommonJS modules can always be imported via the default export, for example using:
> 
> import pkg from 'vue-i18n/dist/vue-i18n.runtime.esm-bundler.js';
> const { createI18n, useI18n } = pkg;
> 
>     at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)
>     at async ModuleJob.run (node:internal/modules/esm/module_job:194:5)
>     at async Promise.all (index 0)
>     at async ESMLoader.import (node:internal/modules/esm/loader:409:24)
>     at async build (file:///Users/mhooshdar/Desktop/Projects/vuilerplate/node_modules/.pnpm/vite-ssg@0.20.2_bc535nzjtcqlryzrekyvursaoq/node_modules/vite-ssg/dist/chunks/build.mjs:171:87)
>     at async Object.handler (file:///Users/mhooshdar/Desktop/Projects/vuilerplate/node_modules/.pnpm/vite-ssg@0.20.2_bc535nzjtcqlryzrekyvursaoq/node_modules/vite-ssg/dist/node/cli.mjs:20:3)
> ```

@mHooshdar  did figure this out? I was only able to get this working by specifying `runtimeOnly: false` which kind of defeats the purpose of this option I guess.
